#!/usr/bin/env python3
"""Build the synth app for the current platform.

macOS:   xcodebuild on the Xcode project generated by bootstrap.py

The binary lands in synth/bin/ next to the data/ folder (samples etc.),
which is the runnable layout openFrameworks expects.

Usage:
  python3 scripts/build.py            build (Release)
  python3 scripts/build.py --debug    build Debug
"""

import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
APP_DIR = ROOT / "synth"
APP_NAME = "synth"


def log(msg):
    print(f"[build] {msg}", flush=True)


def die(msg):
    print(f"[build] ERROR: {msg}", file=sys.stderr, flush=True)
    sys.exit(1)


def build_macos(config):
    project = APP_DIR / f"{APP_NAME}.xcodeproj"
    if not project.exists():
        die(f"{project} not found — run scripts/bootstrap.py first")
    log(f"xcodebuild {config} ...")
    subprocess.run(
        ["xcodebuild", "-project", str(project), "-configuration", config,
         "-jobs", str(os.cpu_count() or 4), "build"],
        cwd=APP_DIR, check=True,
    )
    suffix = "Debug" if config == "Debug" else "Release"
    # oF's Xcode template names the bundle <target><suffix>.app in bin/
    for candidate in (APP_DIR / "bin" / f"{APP_NAME}{suffix}.app",
                      APP_DIR / "bin" / f"{APP_NAME}.app"):
        if candidate.exists():
            return candidate / "Contents" / "MacOS" / candidate.stem
    die(f"build finished but no app bundle found in {APP_DIR / 'bin'}")


def main():
    args = set(sys.argv[1:])
    config = "Debug" if "--debug" in args else "Release"

    if sys.platform != "darwin":
        die(f"unsupported platform: {sys.platform} (macOS only)")

    binary = build_macos(config)

    log(f"built {binary}")


if __name__ == "__main__":
    main()
